# Generated by Django 3.0.6 on 2020-05-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_reading', '0002_file_name_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_name',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file_name',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
